#!/bin/bash
#$#HEADER-START
# vim:set expandtab ts=4 sw=4 ai ft=python:
#
#     Reflex Configuration Event Engine
#
#     Copyright (C) 2016 Brandon Gillespie
#
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU Affero General Public License as published
#     by the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU Affero General Public License for more details.
#
#     You should have received a copy of the GNU Affero General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#$#HEADER-END

banner() {
    echo "-------------------------------------------------------------------------------"
}

if [ ! -f .testbase ]; then
	echo "Must be run from the working directory of the test folder"
	exit 1
fi
#if [ ! -f ~/.reflex/cfg ]; then
#    echo "Initializing reflex with null configuration"
#    ../bin/reflex config set REFLEX_URL=http://localhost/
#fi

# for when we test ourself
unset APP_CFG_BASE
unset APP_RUN_BASE
unset APP_RUN_ROOT

export TESTROOT=$(pwd)
total=0
for d in *; do
	cd $TESTROOT
	if [ -d $d ]; then
		cd $TESTROOT/$d
		banner
		echo "-- $d"
		./test
		total=$(expr $total + $?)
	fi
done

banner
echo "summary: $total"
exit $total
