#!/usr/bin/env python3
#$#HEADER-START
# vim:set expandtab ts=4 sw=4 ai ft=python:
#
#     Reflex Configuration Event Engine
#
#     Copyright (C) 2016 Brandon Gillespie
#
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU Affero General Public License as published
#     by the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU Affero General Public License for more details.
#
#     You should have received a copy of the GNU Affero General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#$#HEADER-END

# common includes
import sys
import os
import argparse
import doctest
import subprocess
from subprocess import *
import hashlib
import shutil
import json
import re
import base64
import io

rfx_base = "../../"
rfx_lib = rfx_base + "/lib/rfx/"
sys.path.append(rfx_base + '/lib')

import rfx
from rfx.test import *
from rfx.backend import Engine

################################################################################
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--debug", action='append')
    parser.add_argument("--noclean", action='store_true')
    parser.add_argument("--nounit", action='store_true')

    args = parser.parse_args()
    base = rfx.Base(debug=args.debug).cfg_load()
    base.timestamp = False # so our output is not altered by timestamps
    base.term_width = 80
    base.notifyfd = io.StringIO()
    base.outputfd = io.StringIO()

    tap = TAP()

    db = Engine(base=base)
    test_name = "_rfx-test_"
    bpath = Action.action_dir

#    def clean():
#        tap.trap(db.delete_object, "config", test_name + "-file", notify=False)

    def rm(file):
        try:
            os.unlink(file)
            return 1
        except:
            return 0

    if not args.nounit:
        tap.unit(rfx_lib, "monitor.py", exit_on_fail=True)
        rm('test.log')

    ###########################################################################
    # preparations
    test_basics = True
    reset_build = True

    if not args.noclean:
        clean()
        shutil.rmtree(bpath)

    tap.exit()

################################################################################
if __name__ == "__main__":
    main()

