#!/bin/bash

if [ $1 ]; then
	images="$@"
else
	images="tools engine"
fi

if [ -f actions.json ]; then
	cd ..
elif [ ! -f .pkg/actions.json ]; then
	echo "Unable to find .pkg/Dockerfile.*"
	exit 1
fi

for type in $images; do
	docker build -f .pkg/Dockerfile.$type -t reflexsc/$type .
done

