FROM python:3.5.2-alpine

RUN apk add --no-cache libffi openssl vim

RUN apk add --no-cache --virtual .build-deps \
        bash curl tar gcc libc-dev libffi-dev \
        linux-headers make python3-dev

# the actual reflex command
RUN pip3 --no-cache-dir install rfxcmd
RUN rm -rf ~/.pip/cache $PWD/build/

RUN apk del .build-deps && rm -rf ~/.cache

CMD ["reflex"]
