FROM reflexsc/engine

WORKDIR /app/reflex

RUN su mysql /usr/bin/mysql_install_db

#COPY .pkg/reflex-engine-demo bin
#RUN ln -s /app/reflex/bin/reflex-engine-demo /usr/local/bin/reflex-engine-demo

COPY .pkg/reflex-engine-demo /etc/minit/startup
#COPY minit /sbin/minit

CMD ["/sbin/minit"]
#CMD ["/usr/local/bin/reflex-engine-demo"]
