#!/bin/sh

# problems with bringing mysql in via pip, so do by hand

python=$1

sed -i -e 's!^mysql:x\(.*\)/sbin/nologin!mysql:x\1/bin/ash!' /etc/passwd

chmod 777 /run
owd=$(pwd)
mkdir temp
cd temp
latest=mysql-connector-latest.tar.gz
url=https://dev.mysql.com/get/Downloads/Connector-Python/mysql-connector-python-2.1.3.tar.gz
curl -L -o $latest $url
tar -xzf $latest


cd mysql-connector-python-*

if [ $MYSQL_CAPI ]; then
	 $python setup.py install --with-mysql-capi=$MYSQL_CAPI
else
	 $python setup.py install
fi
cd $owd
rm -rf temp
