#!/bin/sh

config='
{"sensitive":{"config":{
 "db": {
    "database": "reflex_engine",
    "user": "root"
 }
}}}
'

cd /usr
su mysql /usr/bin/mysqld_safe --datadir=/var/lib/mysql &

echo "create database reflex_engine;" | mysql -u root

echo "$config" | exec reflex-engine --cfgin start
