# this is for docker engine as a server
version: '3.2'
services:
  engine:
    image: your-repo/reflex:prd
    entrypoint: /usr/bin/reflex-engine
    environment:
      - PYTHONUNBUFFERED=true
    ports:
      - published: 4234
        target: 54000
        mode: host
    deploy:
# use what makes sense for your configuration
#      placement:
#        constraints:
#          - node.role == worker
#          - engine.labels.zone == mgz
#          - engine.labels.region == p1
#      replicas: 3
#      update_config:
#        parallelism: 1
#        delay: 30s
#        max_failure_ratio: 0
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    # setup a docker secret with the engine config
    # see example file: REFLEX_ENGINE_CONFIG.json
    secrets:
      - source: reflex-cfg
        target: REFLEX_ENGINE_CONFIG

secrets:
  reflex-cfg:
    external: true
